# Generated by Django 4.2.10 on 2024-08-22 07:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_balance_user_alter_subscription_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='is_valid',
            field=models.BooleanField(default=False, verbose_name='Доступ'),
        ),
        migrations.AlterField(
            model_name='balance',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(fields=('user', 'course'), name='subscription_unique'),
        ),
    ]
